/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jt.lumibright;

import javax.swing.JLabel;

/**
 *
 * @author superman
 */
public class LegendPanel extends javax.swing.JPanel {

    /**
     * Creates new form LegendPanel
     */
    public LegendPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLegend = new javax.swing.JLabel();

        setFocusable(false);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 400));

        lblLegend.setBackground(new java.awt.Color(255, 255, 0));
        lblLegend.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLegend.setText("     Press F2 to Edit     Press F9 to Save     Press <Tab> to Navigate");
        lblLegend.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblLegend.setFocusable(false);
        lblLegend.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLegend, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 395, Short.MAX_VALUE)
                .addComponent(lblLegend, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLegend;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblLegend() {
        return lblLegend;
    }
}
