/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jt.lumibright;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.*;

/**
 *
 * @author superman
 */
public class LineDownPanel extends javax.swing.JPanel {

    private Timer textTimer;
    private Timer blinkingTimer;
    private CountTimerAction timerAction;
    private BlinkingTimerAction blinkingTimerAction;

    /**
     * Creates new form LineDownPanel
     */
    public LineDownPanel() {
        initComponents();
        timerAction = new CountTimerAction(lblTimer);
        blinkingTimerAction = new BlinkingTimerAction(linePanel);
        
        textTimer = new Timer(1000, timerAction);
        blinkingTimer = new Timer(300, blinkingTimerAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linePanel = new javax.swing.JPanel();
        lblLineDown = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        modePanel = new javax.swing.JPanel();
        lblMode = new javax.swing.JLabel();
        partPanel = new javax.swing.JPanel();
        lblPart = new javax.swing.JLabel();
        timerPanel = new javax.swing.JPanel();
        lblTimer = new javax.swing.JLabel();

        linePanel.setBackground(Color.GREEN);
        linePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        linePanel.setFocusable(false);

        lblLineDown.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblLineDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineDown.setText("Normal");
        lblLineDown.setFocusable(false);

        javax.swing.GroupLayout linePanelLayout = new javax.swing.GroupLayout(linePanel);
        linePanel.setLayout(linePanelLayout);
        linePanelLayout.setHorizontalGroup(
            linePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLineDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        linePanelLayout.setVerticalGroup(
            linePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLineDown, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        textPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textPanel.setFocusable(false);

        modePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMode.setText("M");

        javax.swing.GroupLayout modePanelLayout = new javax.swing.GroupLayout(modePanel);
        modePanel.setLayout(modePanelLayout);
        modePanelLayout.setHorizontalGroup(
            modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblMode, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );
        modePanelLayout.setVerticalGroup(
            modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
            .addGroup(modePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblMode, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );

        partPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPart.setText("TT-TT");

        javax.swing.GroupLayout partPanelLayout = new javax.swing.GroupLayout(partPanel);
        partPanel.setLayout(partPanelLayout);
        partPanelLayout.setHorizontalGroup(
            partPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(partPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblPart, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );
        partPanelLayout.setVerticalGroup(
            partPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
            .addGroup(partPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblPart, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                .addComponent(partPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(partPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        timerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        timerPanel.setFocusable(false);

        lblTimer.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("00:00:00");
        lblTimer.setToolTipText("");
        lblTimer.setFocusable(false);

        javax.swing.GroupLayout timerPanelLayout = new javax.swing.GroupLayout(timerPanel);
        timerPanel.setLayout(timerPanelLayout);
        timerPanelLayout.setHorizontalGroup(
            timerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        timerPanelLayout.setVerticalGroup(
            timerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timerPanelLayout.createSequentialGroup()
                .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(linePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblPart() {
        return lblPart;
    }

    public JLabel getLblMode() {
        return lblMode;
    }

    public JLabel getLblLineDown() {
        return lblLineDown;
    }

    public JLabel getLblTimer() {
        return lblTimer;
    }

    public void startTimer() {
        lblLineDown.setText("Line Down!");
        textTimer.start();
        blinkingTimer.start();
    }

    public void stopTimer() {
        textTimer.stop();
        blinkingTimer.stop();
        linePanel.setBackground(Color.RED);
    }

    public void resetTimer() {
        timerAction.resetTimer();
        lblTimer.setText("00:00:00");
        lblLineDown.setText("Normal");
        linePanel.setBackground(Color.GREEN);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLineDown;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblPart;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JPanel linePanel;
    private javax.swing.JPanel modePanel;
    private javax.swing.JPanel partPanel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JPanel timerPanel;
    // End of variables declaration//GEN-END:variables

    private static class CountTimerAction implements ActionListener {

        private DecimalFormat timeFormatter = new DecimalFormat("00");
        private int accumulatedSeconds;
        private JLabel label;

        public CountTimerAction(JLabel label) {
            this.label = label;
        }

        public void resetTimer() {
            accumulatedSeconds = 0;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            accumulatedSeconds++;
            int calculation = accumulatedSeconds;
            
            long hour = calculation / (60 * 60);
            calculation = Math.round(calculation % (60 * 60));
            long minutes = calculation / (60);
            calculation = Math.round(calculation % (60));
            long seconds = calculation;

            label.setText(timeFormatter.format(hour) + ":"
                    + timeFormatter.format(minutes) + ":"
                    + timeFormatter.format(seconds));
        }

    }

    private static class BlinkingTimerAction implements ActionListener {

        private javax.swing.JPanel panel;
        private int current = 0;

        public BlinkingTimerAction(javax.swing.JPanel panel) {
            this.panel = panel;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            if (current == 0) {
                panel.setBackground(Color.RED);
                current = 1;
            } else {
                panel.setBackground(Color.WHITE);
                current = 0;
            }
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Main method">//GEN-BEGIN:main
    public static void main(String[] args) {
        JFrame f = new JFrame("Panel Example");
        f.setDefaultCloseOperation(2);

        final LineDownPanel panel = new LineDownPanel();
        InputMap im = panel.getInputMap(WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = panel.getActionMap();

        AbstractAction startAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.startTimer();
            }
        };

        AbstractAction stopAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.stopTimer();
            }
        };

        AbstractAction resetAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.resetTimer();
            }
        };

        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "F2");
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "F3");
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "F4");
        am.put("F2", startAction);
        am.put("F3", stopAction);
        am.put("F4", resetAction);

        f.add(panel);
        f.pack();
        f.setVisible(true);
    }// </editor-fold>//GEN-END:main

}
